INSERT INTO news (title, description, image_url) VALUES ('China confines almost a million people in the east of the country and increases restrictions', 'The city of Zhengzhou, in eastern China, joins the increase in restrictions that China is imposing in the face of coronavirus outbreaks. Nearly a million residents of the Zhongyuan district have been ordered to stay home from Monday, except for times when they have to undergo coronavirus tests, according to local media.', 'https://image.ondacero.es/clipping/cmsimages02/2022/10/17/BF222101-B7D9-4A98-9C28-9F4B1DBF53F3/gente-hace-cola-hacerse-prueba-pcr-coronavirus-china_97.jpg?crop=1920,1080,x0,y53&width=1600&height=900&optimize=high&format=webply');
INSERT INTO news (title, description, image_url) VALUES ('BQ.1, the new variant of COVID-19 circulating in Spain: what are its symptoms?', 'The BQ.1 variant of the coronavirus has been detected for the first time in wastewater in Catalonia, according to the Secretary of Public Health, Carmen Cabezas, in an interview with RAC1 although, for now, no case of infection in people is known. This is a descendant of the BA.5 variant of Omicron.\n\nAnd it is that COVID-19 is still present among us. The latest figures published by the Ministry of Health, dated October 14, show a rise in the incidence of the coronavirus, more specifically double the number of cases compared to the previous week, with 20,652 compared to 10,843.', 'https://img.asmedia.epimg.net/resizer/-gotA4sBu6rZxT2eHu4Mvxeev6A=/736x414/cloudfront-eu-central-1.images.arcpublishing.com/diarioas/UO7IVK65OBMMBFLMEGIZMJLG5Y.jpg');
INSERT INTO news (title, description, image_url) VALUES ('Health vaccinated 95,102 people against the flu during the first week of the campaign in the Valencian Community', 'The Ministry of Universal Health and Public Health has immunized 95,102 people in the Valencian Community during the first week of the flu vaccination campaign. Specifically, they are 20,000 doses more than during the first week of the 2021/22 campaign, when 75,000 vaccines were inoculated between October 26 and November 1.', 'https://static.eldiario.es/clip/ebfb7804-6594-43bd-b493-ab561ea08181_16-9-discover-aspect-ratio_default_0.jpg');
INSERT INTO news (title, description, image_url) VALUES ('The world is running out of helium. Here is why doctors are worried.', 'A global helium shortage has doctors worried about one of the natural gas’s most essential, and perhaps unexpected, uses: MRIs. Strange as it sounds, the lighter-than-air element that gives balloons their buoyancy also powers the vital medical diagnostic machines. An MRI can’t function without some 2,000 liters of ultra-cold liquid helium keeping its magnets cool enough to work. But helium — a nonrenewable element found deep within the Earth’s crust — is running low, leaving hospitals wondering how to plan for a future with a much scarcer supply', 'https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1240w,f_auto,q_auto:best/rockcms/2022-10/102022-HeliumShortageMRIs-JN-91db91.jpg');
INSERT INTO news (title, description, image_url) VALUES ('Covid was a contributing factor in 25% of maternal deaths in 2020 and 2021', 'Covid-19 drove a dramatic increase in the number of women who died from pregnancy or childbirth complications in the U.S. last year, a crisis that has disproportionately claimed Black and Hispanic women as victims, according to a government report released Wednesday.\n\nThe report lays out grim trends across the country for expectant mothers and their newborn babies.\n\nIt finds that pregnancy-related deaths have spiked nearly 80% since 2018, with Covid-19 being a factor in a quarter of the 1,178 deaths reported last year. The percentage of preterm and low birthweight babies also went up last year, after holding steady for years.', 'https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1240w,f_auto,q_auto:best/rockcms/2022-10/221020-Womens-Clinic-Mississippi-heartbeat-fetus-pregant-2021-ac-509p-2b01f5.jpg');
INSERT INTO news (title, description, image_url) VALUES ('CDC group endorses adding Covid shots to recommended vaccine schedule', 'An advisory committee to the Centers for Disease Control and Prevention voted Thursday in favor of adding the Covid vaccine to the recommended immunization schedule for children and adults.\n\nChildren 6 months and older, as well as adults, should get the Covid vaccine, plus boosters, when they are eligible for it, the Advisory Committee on Immunization Practices said in an unanimous vote.\n\nFull coverage of the Covid-19 pandemic\n\nThe CDC advisory committee meets every year to review the vaccination schedule and make updates. The schedule is meant to help guide doctors in determining when to administer a number of important vaccinations, particularly for children, including vaccinations for polio, measles, whooping cough and tetanus.', 'https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1240w,f_auto,q_auto:best/rockcms/2022-10/221020-children-covid-vaccine-mn-0915-8f39f8.jpg');

INSERT INTO patients (age, dni, email, name, password, user_type, birth_date, bmi, height, phone_number, weight) VALUES (70, '71524318', 'mike@gmail.com', 'Mike Miller', '123', 0, '1957-10-22', 25.354, 170,'987289653', 60);
INSERT INTO patients (age, dni, email, name, password, user_type, birth_date, bmi, height, phone_number, weight) VALUES (25, '54254646', 'anasiu@gmail.com', 'Ana Stacia', 'ana54321', 0, '1998-03-12', 25.354, 159,'936478492', 50);
INSERT INTO patients (age, dni, email, name, password, user_type, birth_date, bmi, height, phone_number, weight) VALUES (40, '98285831', 'luis@gmail.com', 'Luis Joaquin', '987', 0, '1980-03-15', 25.354, 190,'99999677', 65);
INSERT INTO patients (age, dni, email, name, password, user_type, birth_date, bmi, height, phone_number, weight) VALUES (30, '71536571', 'jenkins@gmail.com', 'Jenkins López', 'password123', 0, '1993-05-02', 25.354, 160,'981076549', 67);
INSERT INTO patients (age, dni, email, name, password, user_type, birth_date, bmi, height, phone_number, weight) VALUES (18, '77488901', 'joel@gmail.com', 'Joel Martinez', 'secreto12345', 0, '2005-01-27', 25.354, 168,'900615289', 80);
INSERT INTO patients (age, dni, email, name, password, user_type, birth_date, bmi, height, phone_number, weight) VALUES (60, '66718314', 'vanessa@gmail.com', 'Vanessa Gutierrez', 'contraseñacreta', 0, '1967-06-08', 25.354, 158,'999888777', 49);

INSERT INTO doctors (age, dni, email, name, password, user_type, description, doctor_fee, experience_years, patients_assisted, profile_photo, speciality) VALUES (45, '726384821', 'doctor1@example.com', 'Dr. Jonatan Mondragon', '12345', 1, 'Más de 15 años de experiencia en dentista', 80, 15, 78, 'photo2.jpg', 'Dentista');
INSERT INTO doctors (age, dni, email, name, password, user_type, description, doctor_fee, experience_years, patients_assisted, profile_photo, speciality) VALUES (45, '87654321B', 'doctor2@example.com', 'Dra. Ana González', 'password456', 1, 'Más de 15 años de experiencia en cardiología', 80, 15, 78, 'photo2.jpg', 'Cardiología');
INSERT INTO doctors (age, dni, email, name, password, user_type, description, doctor_fee, experience_years, patients_assisted, profile_photo, speciality) VALUES (40, '65432198C', 'doctor3@example.com', 'Dr. Carlos Martínez', 'password789', 1, 'Experto en cirugía plástica', 120, 20, 200, 'photo3.jpg', 'Cirugía plástica');
INSERT INTO doctors (age, dni, email, name, password, user_type, description, doctor_fee, experience_years, patients_assisted, profile_photo, speciality) VALUES (55, '12345678A', 'doctor@example.com', 'Dr. Juan Pérez', 'password123', 1, 'Especialista en traumatología', 50, 10, 134, 'photo.jpg', 'Traumatología');
INSERT INTO doctors (age, dni, email, name, password, user_type, description, doctor_fee, experience_years, patients_assisted, profile_photo, speciality) VALUES (38, '78965432D', 'doctor4@example.com', 'Dra. Isabel García', 'password012', 1, 'Atención personalizada y enfocada en el bienestar del paciente', 60, 8, 300, 'photo4.jpg', 'Medicina general');
INSERT INTO doctors (age, dni, email, name, password, user_type, description, doctor_fee, experience_years, patients_assisted, profile_photo, speciality) VALUES (50, '13579246E', 'doctor5@example.com', 'Dr. Pedro Sánchez', 'password345', 1, 'Graduado en la Universidad de Harvard', 100, 25, 300, 'photo5.jpg', 'Neurología');

INSERT INTO reviews (description, rating, doctor_id, patient_id) VALUES ('GOOD ATENTION 10/10', 5, 1, 1);
INSERT INTO reviews (description, rating, doctor_id, patient_id) VALUES ('NICE ATENTION 10/10', 5, 1, 1);
INSERT INTO reviews (description, rating, doctor_id, patient_id) VALUES ('PERFECT ATENTION 10/10', 5, 2, 1);
INSERT INTO reviews (description, rating, doctor_id, patient_id) VALUES ('BAD ATENTION 2/10', 1, 3, 1);
INSERT INTO reviews (description, rating, doctor_id, patient_id) VALUES ('COULD BE BETTER 5/10', 3, 1, 1);

INSERT INTO appointments (date, start_time, end_time, doctor_id, patient_id) VALUES ('2023-02-23', '10:00', '12:00', 3, 2);
INSERT INTO appointments (date, start_time, end_time, doctor_id, patient_id) VALUES ('2023-12-20', '14:00', '16:00', 1, 2);
INSERT INTO appointments (date, start_time, end_time, doctor_id, patient_id) VALUES ('2023-06-13', '15:00', '18:00', 2, 3);
INSERT INTO appointments (date, start_time, end_time, doctor_id, patient_id) VALUES ('2023-02-31', '13:00', '15:00', 3, 1);